version: '3.4'
services:
  site:
    image: canelrom1/apache2-php7:latest
    depends_on:
      - db
    networks:
      - lan
      - wan
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./site-storage:/var/www/html
    #environment:
      ## Mail configuration
      #SMTP_HOST: "smtp.domain.tld"
      #SMTP_PORT: "587"
      #SMTP_USER: "user@domain.tld"
      #SMTP_PASSWORD: "mypassword"
      #SMTP_MAILFROM: "mailfrom@domain.tld"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 0s

  db:
    image: mariadb:latest
    networks:
      - lan
    volumes:
      - ./db-storage:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "database"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 0s

  adminer:
    image: adminer:latest
    depends_on:
      - db
    networks:
      - lan
      - wan
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 0s

networks:
  wan:
  lan:

volumes:
  db-storage:
    driver: local
  site-storage:
    driver: local

# vim: ft=yaml tw=80 et ts=2 sw=2 sts=2
